*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jan 25 20:04:03 2021] ***
compiled with version: Apple LLVM 12.0.0 (clang-1200.0.32.27) on 18 January 2021 16:18:34
os: Darwin-19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
nodename: Aidens-MacBook-Pro.local
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /Users/aiden_zcf/PycharmProjects/Tmooc/python_leanring_code/month04/Django/django8/mysite7/mysite7
writing pidfile to uwsgi.pid
detected binary path: /opt/anaconda3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /Users/aiden_zcf/PycharmProjects/Tmooc/python_leanring_code/month04/Django/django8/mysite7
your processes number limit is 1392
your memory page size is 4096 bytes
detected max file descriptor number: 2560
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:54376 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Aug 13 2019, 15:17:50)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Python main interpreter initialized at 0x7feb19f05440
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166656 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
added /opt/anaconda3/lib/python3.7/site-packages/ to pythonpath.
Traceback (most recent call last):
  File "/Users/aiden_zcf/PycharmProjects/Tmooc/python_leanring_code/month04/Django/django8/mysite7/mysite7/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/opt/anaconda3/lib/python3.7/site-packages/Django-2.2.17-py3.7.egg/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/opt/anaconda3/lib/python3.7/site-packages/Django-2.2.17-py3.7.egg/django/utils/version.py", line 1, in <module>
    import datetime
  File "/opt/anaconda3/lib/python3.7/datetime.py", line 8, in <module>
    import math as _math
ImportError: dlopen(/opt/anaconda3/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so, 2): Symbol not found: _PyExc_MemoryError
  Referenced from: /opt/anaconda3/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
  Expected in: flat namespace
 in /opt/anaconda3/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18743)
spawned uWSGI worker 1 (pid: 18744, cores: 2)
spawned uWSGI http 1 (pid: 18745)
--- no python application found, check your startup logs for errors ---
[pid: 18744|app: -1|req: -1/1] 127.0.0.1 () {52 vars in 1108 bytes} [Mon Jan 25 20:04:09 2021] GET /test_upload => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 18745)
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jan 25 20:06:57 2021] ***
compiled with version: Apple LLVM 12.0.0 (clang-1200.0.32.27) on 18 January 2021 16:18:34
os: Darwin-19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
nodename: Aidens-MacBook-Pro.local
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /Users/aiden_zcf/PycharmProjects/Tmooc/python_leanring_code/month04/Django/django8/mysite7/mysite7
writing pidfile to uwsgi.pid
detected binary path: /opt/anaconda3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /Users/aiden_zcf/PycharmProjects/Tmooc/python_leanring_code/month04/Django/django8/mysite7
your processes number limit is 1392
your memory page size is 4096 bytes
detected max file descriptor number: 2560
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:55021 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Aug 13 2019, 15:17:50)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Python main interpreter initialized at 0x7f8a136056f0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166656 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
added /opt/anaconda3/lib/python3.7/site-packages/ to pythonpath.
Traceback (most recent call last):
  File "./mysite7/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/opt/anaconda3/lib/python3.7/site-packages/Django-2.2.17-py3.7.egg/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/opt/anaconda3/lib/python3.7/site-packages/Django-2.2.17-py3.7.egg/django/utils/version.py", line 1, in <module>
    import datetime
  File "/opt/anaconda3/lib/python3.7/datetime.py", line 8, in <module>
    import math as _math
ImportError: dlopen(/opt/anaconda3/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so, 2): Symbol not found: _PyExc_MemoryError
  Referenced from: /opt/anaconda3/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
  Expected in: flat namespace
 in /opt/anaconda3/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
unable to load app 0 (mountpoint='') (callable not found or import error)
Traceback (most recent call last):
  File "/Users/aiden_zcf/PycharmProjects/Tmooc/python_leanring_code/month04/Django/django8/mysite7/mysite7/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/opt/anaconda3/lib/python3.7/site-packages/Django-2.2.17-py3.7.egg/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/opt/anaconda3/lib/python3.7/site-packages/Django-2.2.17-py3.7.egg/django/utils/version.py", line 1, in <module>
    import datetime
  File "/opt/anaconda3/lib/python3.7/datetime.py", line 8, in <module>
    import math as _math
ImportError: dlopen(/opt/anaconda3/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so, 2): Symbol not found: _PyExc_MemoryError
  Referenced from: /opt/anaconda3/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
  Expected in: flat namespace
 in /opt/anaconda3/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18828)
spawned uWSGI worker 1 (pid: 18829, cores: 2)
spawned uWSGI http 1 (pid: 18830)
--- no python application found, check your startup logs for errors ---
[pid: 18829|app: -1|req: -1/1] 127.0.0.1 () {52 vars in 1108 bytes} [Mon Jan 25 20:07:01 2021] GET /test_upload => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 18829|app: -1|req: -1/2] 127.0.0.1 () {52 vars in 1108 bytes} [Mon Jan 25 20:07:03 2021] GET /test_upload => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 18830)
worker 1 buried after 1 seconds
goodbye to uWSGI.
